name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository using the latest version of actions/checkout
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker using secrets stored in GitHub
      - run: docker login -u ${{ secrets.SARANSH138 }} -p ${{ secrets.HIMALAYAN2001 }}

      # Step 3: Build the Docker image using the specified Dockerfile
      - run: docker build -t demo/react-test -f Dockerfile.dev .

      # Step 4: Run the Docker container and execute tests
      - run: docker run -e CI=true demo/react-test npm test
