name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository using the latest version of actions/checkout
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker using secrets stored in GitHub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      # Step 3: Build the Docker image using the specified Dockerfile
      - name: Build Docker Image
        run: docker build -t demo/react-test -f Dockerfile.dev .

      # Step 4: Run the Docker container and execute tests as
      - name: Run Tests
        run: docker run -e CI=true demo/react-test npm test
